# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-30 05:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0003_auto_20170318_1050'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='department',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='profile', to='company.Department'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='sex',
            field=models.BooleanField(default=0),
        ),
    ]
