# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-30 12:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0004_auto_20170330_1327'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='sex',
            field=models.BooleanField(default=0, verbose_name='性别'),
        ),
    ]
