# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-24 11:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ModulePermission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'permissions': (('user.user', '用户管理'), ('company.company', '组织管理-组织管理'), ('company.department', '组织管理-部门管理')),
            },
        ),
    ]
